version: '3.8'

services:
  backend:
    build:
      context: ./backend  # Path to your Go backend folder
    image: rubini04/backend:latest  # Tag with your username.. Image creation for frontend
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_HOST=db   
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=rubini # Specify the password 
      - POSTGRES_DB=task  # Specify the database name here
    depends_on:
      - db
    networks:
      - app-network

  frontend:
    build:
      context: ./task1  # Path to your React frontend folder
    image: rubini04/frontend:latest    # Image creation for frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network

  db:
    image: rubini04/postgres:latest     # Image creation for Database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: rubini
      POSTGRES_DB: task
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
